# Defaults main.yml for common role

common_git_repos:
  - "https://github.com/ocp4-disconnected/collection.git"
  - "https://github.com/ocp4-disconnected/config.git"

## Global variables used by most/all roles
common_install_dir: "{{ ansible_user_dir }}"
common_trident_version: v24.06.0
common_oc_mirror_v2: true
common_content_pull: false

## OpenShift Connected Install Variables
common_openshift_interface: eno1
common_cluster_domain: example.com
commond_connected_cluster: false
common_openshift_cluster_install_dir: "{{ common_install_dir }}/install-{{ ansible_date_time.date }}"

## Openshift Disconnected Install Variables
common_openshift_release: 4.14.16
common_oc_mirror_release: 4.17.8
common_previous_openshift_release: 4.14.16
common_registry_volume: /pods/registry #### NEED TO RE-EVALUATE. FOR SOME REASON AGENT INSTALL USES THIS
common_ip_space: 192.168.69
common_subnet_mask: 24
common_gateway_ip: '{{ common_ip_space }}.1'
common_ssh_key: "{{ ansible_user_dir + '/.ssh/id_rsa' }}"
common_registry_port: 5000