---
# defaults file for day1_automation
helm_values_filepath: "{{ playbook_dir }}/../helm/openshift-gitops/ansible_values.yaml"
helm_day1_release_name: gitops-day1
helm_options: "-v ./ansible_ansible_values.yaml --wait-for-jobs"
auto_run_helm: true