---
- when: generate_passwd == true and htpasswd_password is not defined
  name: "Generate random password"
  ansible.builtin.set_fact:
    htpasswd_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits']) }}" 

 #- when: htpasswd_password is defined
 #  ansible.builtin.debug:
 #    msg: "Password is: {{ htpasswd_password }}"

- name: "Check if passlib is installed"
  community.general.pip_package_info:
    clients: ['pip3']
  register: package_info

- when: htpasswd_password is defined and package_info.packages.pip3.passlib is defined
  name: "Generate htpasswd file"
  ansible.builtin.htpasswd:
    create: true
    state: present
    path: "{{ htpasswd_file_path }}"
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_password }}"

- when: package_info.packages.pip3.passlib is not defined
  name: "Generate htpasswd file"
  ansible.builtin.shell:
    cmd: "/bin/htpasswd  -c -B -b {{ htpasswd_file_path }} {{ htpasswd_user }} {{ htpasswd_password }}"
