---
- name: "Generate secret from htpasswd file"
  ansible.builtin.template:
    src: templates/htpasswd-secret.j2
    dest: "{{ htpasswd_secret_file_dest }}" 

- name: "k8s innit"
  ansible.builtin.debug:
    msg: "{{ package_info.packages.pip3.kubernetes }}"
  when: package_info.packages.pip3.kubernetes is defined

- name: "Apply secret to cluster"
  kubernetes.core.k8s:
    state: present
    src: "{{ htpasswd_secret_file_dest }}"
  when: package_info.packages.pip3.kubernetes is defined  

- name: "Apply secret to cluster"
  ansible.builtin.shell:
    cmd: "oc apply -f {{ htpasswd_secret_file_dest }}"
  when: package_info.packages.pip3.kubernetes is not defined

