---
# tasks file for htpasswd

#Check if required modules are installed
- name: "Get installed package information"
  community.general.pip_package_info:
    clients: ['pip3']
  register: package_info

- name: "Create htpasswd file"
  ansible.builtin.include_tasks: create_htpasswd_file.yml
  when: create_htpasswd_file == true

- name: "Create htpass secret"
  ansible.builtin.include_tasks: create_htpass_secret.yml
  when: create_htpass_secret == true

- name: "Create oauth config"
  ansible.builtin.include_tasks: create_oauth_config.yml
  when: create_oauth_config == true

- name: "Create group"
  ansible.builtin.include_tasks: create_group.yml
  when: create_group == true

- name: "Create role binding"
  ansible.builtin.include_tasks: create_role_binding.yml
  when: create_role_binding == true

- name: "Display admin password"
  ansible.builtin.debug:
    msg: "Admin password is: {{ htpasswd_password }}"
  when: htpasswd_password is defined

- name: "Clean up htpasswd file"
  ansible.builtin.file:
    path: "{{ htpasswd_file_path }}"
    state: absent

- name: "Clean up secret file"
  ansible.builtin.file:
    path: "{{ htpasswd_secret_file_dest }}"
    state: absent

- name: "Clean up group file"
  ansible.builtin.file:
    path: "{{ openshift_group_file_dest }}"
    state: absent

- name: "Clean up oauth file"
  ansible.builtin.file:
    path: "{{ htpass_oauth_file_dest }}"
    state: absent

- name: "Clean up crb file"
  ansible.builtin.file:
    path: "{{ openshift_crb_file_dest }}"
    state: absent