---
    - name: Run git status and check for detached HEAD
      shell: git status
      register: git_status_output
      changed_when: false

    - name: Determine if in a detached HEAD state
      set_fact:
        git_detached_state: "{{ 'Not currently on any branch.' in git_status_output.stdout }}"

    - name: Get the current tag if in detached HEAD state
      shell: git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD
      register: git_tag
      changed_when: false
      when: git_detached_state

    - name: Store the tag in a variable
      set_fact:
        current_tag: "{{ git_tag.stdout }}"
      when: git_detached_state

    - name: Checkout to a new branch using the tag name
      shell: git checkout -b "ansible_run_{{ current_tag }}"
      when: git_detached_state and current_tag | length > 0

    - name: Debug the new branch name
      debug:
        msg: "Checked out to new branch: ansible_run_{{ current_tag }}"
      when: git_detached_state and current_tag | length > 0
